title:              Sam Blog
email:              helloboy3x@gmail.com
description:        A Blog About Everything
author:             Sam Chen
baseurl:            "/sam-blog"
url:                "https://helloboyxxx.github.io"

# Social Profiles
github_username:    helloboyxxx
instagram_username:  sam_yuechen
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

theme: jekyll-theme-clean-blog
